baseURL = 'https://kobamkode.github.io/'
languageCode = 'en-us'
title = 'A Plaintext Quest'
theme = 'typo'

[taxonomies]
tag = 'tags'

# Google analytics code
googleAnalytics = "G-xxxxxxxxx"

[params]
# Meta description
description = ""

# Appearance settings
theme = 'auto'
colorPalette = 'default'
hideHeader = false

# Intro on main page, content is markdown
homeIntroTitle = 'Hi! 👋'
homeIntroContent = """
I’m Mario, a software developer 👨‍💻. I love to learn programming languages and development ecosystem. I understand that there is a lot of knowledge out there to absorb, but I feel like my brain no longer can hold that much information. To help me remember what I have learned each day, I am writing down my brief notes here. ✍️
"""

# Collection to display on home
homeCollectionTitle = 'Today I Learned'
homeCollection = 'til'

# Lists parameters
paginationSize = 100
# listSummaries = true
listDateFormat = '2 Jan 2006'

# Breadcrumbs
breadcrumbs = true

# Social icons
# [[params.social]]
# name = "linkedin"
# url = "https://www.linkedin.com/in/user/"

# [[params.social]]
# name = "medium"
# url = "https://medium.com/@user"

[[params.social]]
name = "github"
url = "https://github.com/kobamkode"

# Main menu pages
[[params.menu]]
name = "home"
url = "/"

# [[params.menu]]
# name = "today i learned"
# url = "/til"

# [[params.menu]]
# name = "about"
# url = "/about"

# Syntax highligth on code blocks
[markup]
[markup.highlight]
style = 'algol'

# Giscus comments
# [params.giscus]
# enable = false
# repo = "user/repo"
# repoid = "repoId"
# category = "General"
# categoryid = "categoryId"
# mapping = "pathname"
# theme = "preferred_color_scheme"
